#!/bin/bash
# Launch the rl+imitation Dyna loop for several independent seeds.
#
#   ./run_seeds.sh              # seeds 1 2 3
#   SEEDS="1 2 3 4 5" ./run_seeds.sh
#   ITERS_TO=4 ./run_seeds.sh   # 5 Dyna iterations each instead of 10
#
# Each seed gets its own results_rlloop_s<N>/ and configdata/pensim_rlloop_s<N>/, so
# the replicates never share a dataset. Sharing one would make iteration k of a seed
# train on episodes generated by a different seed, and the runs would not be
# independent -- which is the whole point of running them.
#
# WHAT VARIES: the policy initialisation, the window draw, the particle sampling and
# the environment reset. Everything else -- eta, alpha_W2, kappa, lambda, the phase
# bounds, the starting world models, the reward GP -- is held fixed.
#
# WHAT TO COMPARE. Yield per iteration across seeds. Every configuration tried so far
# has landed in 2728-3486 against gpei's 3835, so a spread of that size ACROSS SEEDS
# would mean the differences between methods measured to date are run-to-run variance
# rather than real effects. That is worth knowing before drawing conclusions from any
# single run.
set -euo pipefail
cd "$(dirname "$0")"
SEEDS=${SEEDS:-"1 2 3"}
ITERS_FROM=${ITERS_FROM:-0}
ITERS_TO=${ITERS_TO:-9}

echo "launching seeds: $SEEDS   iterations $ITERS_FROM..$ITERS_TO"
echo "(seed 0 is the run already submitted by ./run_rlimit_loop.sh)"
echo
for S in $SEEDS; do
  echo "############ SEED $S"
  SEED=$S ./run_rlimit_loop.sh "$ITERS_FROM" "$ITERS_TO"
  echo
done

echo "=========================================================================="
echo "compare across seeds when they finish:"
echo
echo "  for S in 0 $SEEDS; do"
echo "    echo \"seed \$S:\"; grep -h 'total yield  mean' \\"
echo "      results_rlloop_s\$S/it*_explore_*.out | awk '{print \"   \" \$4}'"
echo "  done"
echo
echo "  # and the per-iteration trend, one line per seed"
echo "  for S in 0 $SEEDS; do"
echo "    printf 'seed %s: ' \$S"
echo "    grep -h 'total yield  mean' results_rlloop_s\$S/it*_explore_*.out \\"
echo "      | sed 's/.*mean=//;s/ .*//' | tr '\\n' ' '; echo"
echo "  done"
echo "=========================================================================="
